travis:
  secure:
    BINSTAR_TOKEN: oUr1GDE0IFWY5Y0GHB6AKHVo4IIaKjPIov9Ea0G43ujYMON7ER5OQ09HoQ0+6wppIPHG5SrRzzoJO0HLhIpFU31SmgQn6JlpCFl9IG8mL0O+amJcj+iTJVE6OPZ5IBpQpwTBOOaacEsN0cjYgTXplkAguuVrJZuKFqSfeQ3Vs/xMvTi6EaZXdWWa9C6eLsFAcGzqXuIcxINgBTI3o+FHpEnqTDYvekM9QFMugCKsk83tmmBWDFAsHIr1xX/ZKBaT37Vu/Au5oz0rOT2WDYTh9P4XQrnV3OsrLG+eu4mRKBidiZFg3kn0KawtR516K/a1UOnyhOqOpDvS44ZTjPs3wnOGzCExiGvsNFHYjf8MNj/PPTS28ClYAa0EXV2LEzmPs3FEYHmh2fFOLdFA5heiDvZ8qrEjOra4QYkp30/sChwrTfz1NOK/ESXOsEySxNr9brnKpmKMgBW+BA3aDjcE9fDBDOq6OBDPJlOKgNCTYeIdRpPhktbbFOlMCvtkE/sRxr1Nb5ETwVbsnlDyxrRfzAssMfzeNhJk0ileGWI7sAZdJbhfVLc93KDS3D6aFpyJUlBkOCPGxCbuyAVNFvPOIJl0TYudUGv6r1mXBNZC6DxmWfpwKywbpiA+8P86Of1LjDeIHt3RWBsuDWPHO1Vk7NpNIrYmTxSZXRy1K55C40g=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
