travis:
  secure:
    BINSTAR_TOKEN: Jj8yw5bBR1nke+7zTAZz0i8Nwq31rR/Z6Xz9YHOwsVkat5ZZ2tw4hAWFzsFQ82xg/docP51g7rwv4Msu8fpuoFj8WY0meMi42LdtK3qle5ORpghPhFCdMAvViIhdjbc6AGz1179JDgfMmy171Sn9SuQFVVxgxzRkC44Nur80OAkNQnLLWuXR5Ylb8J3586g6PYftuDt7ZmNCh1qCNet1dPUQosV/YNXN5zOIfI3RLaF2NHih1ln0V0dEGpODlQiM3p7VV9NcvWkSnXtfein66RjkhMwLSGWaIfE+TpX/qIfGdFjfU+CmMqYBhmnQesxlddF2yR9D39qAoXZ0MvyFpqKBuWUko+U+3jwIWfhBncBMcbPJ+U9RDrLN9xRX9n9CjpKOz0BHVZgJVRRaT0FHcZxngRVW8vRvnPLyslrDUHp6qX2epVD1P92GOxMoVuLjzzPFnKPjAD+ykzpSdLMRbd5S+mzjGMfioXEJWR/Sr2iFs/GUnOjpRn1k93cP7OiLjJf6iic8STN2/OchBjE6Jk/p+Iq242ZaGf8uguEyBYsUSJ665WSr750rxj49+9r3iOmoKFk2BFI5g1Bc3g3YFv7OZOLkYKHfB3Inyp954S3Uz/x7BoaAIDdpD1z/F0Fz9Vqjklp4Ibx0GbeHxOiMVwVwyB5Gu8uJSwZtBIu/zuM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
